# .markdownlint.yaml
default: true

# Line length
MD013: false

# Unordered list indentation
MD007:
  indent: 2

# Multiple headers with same content (allowed for distinct sections)
MD024:
  siblings_only: true

# Inline HTML (allow for <br>, details/summary)
MD033:
  allowed_elements: ["br", "details", "summary", "kbd", "img"]
