"""
Caddy module for reverse proxy.

Handles:
- Caddy installation
- Basic configuration
- Automatic HTTPS
"""

from pathlib import Path

from configurator.modules.base import ConfigurationModule


class CaddyModule(ConfigurationModule):
    """
    Caddy web server and reverse proxy module.

    Caddy provides automatic HTTPS and is easier to configure
    than Nginx for most use cases.
    """

    name = "Caddy"
    description = "Install Caddy reverse proxy"
    priority = 71
    mandatory = False

    def validate(self) -> bool:
        """Validate Caddy prerequisites."""
        # Check if Caddy is already installed
        if self.command_exists("caddy"):
            result = self.run("caddy version", check=False)
            self.logger.info(f"  Found existing Caddy: {result.stdout.strip()}")

        return True

    def configure(self) -> bool:
        """Install and configure Caddy."""
        self.logger.info("Installing Caddy...")

        # 1. Add Caddy repository
        self._add_repository()

        # 2. Install Caddy
        self._install_caddy()

        # 3. Create default configuration
        self._create_config()

        # 4. Configure firewall
        self._configure_firewall()

        # 5. Start service
        self._start_service()

        self.logger.info("✓ Caddy installed")
        return True

    def verify(self) -> bool:
        """Verify Caddy installation."""
        checks_passed = True

        # Check caddy command
        result = self.run("caddy version", check=False)
        if result.success:
            self.logger.info(f"✓ {result.stdout.strip()}")
        else:
            self.logger.error("Caddy not installed!")
            checks_passed = False

        # Check service
        if self.is_service_active("caddy"):
            self.logger.info("✓ Caddy service is running")
        else:
            self.logger.warning("Caddy service is not running")

        return checks_passed

    def _add_repository(self):
        """Add Caddy repository."""
        self.logger.info("Adding Caddy repository...")

        # Install dependencies
        self.install_packages(["debian-keyring", "debian-archive-keyring", "apt-transport-https"])

        # Add GPG key
        self.run(
            "curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | "
            "gpg --dearmor --yes -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg",
            check=True,
        )

        # Add repository
        self.run(
            "curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | "
            "tee /etc/apt/sources.list.d/caddy-stable.list",
            check=True,
        )

        # Update package lists
        self.run("apt-get update", check=True)

        self.logger.info("✓ Caddy repository added")

    def _install_caddy(self):
        """Install Caddy package."""
        self.logger.info("Installing Caddy...")
        self.install_packages(["caddy"], update_cache=False)

    def _create_config(self):
        """Create default Caddyfile."""
        self.logger.info("Creating configuration...")

        # Get domain from config or use placeholder
        domain = self.get_config("domain", "localhost")

        caddyfile = f"""# Caddyfile - Caddy Configuration
# Generated by debian-vps-configurator
# Documentation: https://caddyserver.com/docs/caddyfile

# Global options
{{
    # Email for ACME registration (Let's Encrypt)
    # Uncomment and set your email for automatic HTTPS
    # email your@email.com
    
    # Enable admin API on localhost only
    admin localhost:2019
}}

# Default site (localhost)
:{self.get_config("port", 80)} {{
    root * /var/www/html
    file_server
    
    # Basic security headers
    header {{
        X-Content-Type-Options nosniff
        X-Frame-Options DENY
        Referrer-Policy strict-origin-when-cross-origin
    }}
}}

# Example: Reverse proxy to a local app
# app.example.com {{
#     reverse_proxy localhost:3000
# }}

# Example: Static site with automatic HTTPS
# example.com {{
#     root * /var/www/example.com
#     file_server
#     encode gzip
# }}
"""

        # Create Caddyfile
        caddyfile_path = Path("/etc/caddy/Caddyfile")
        caddyfile_path.write_text(caddyfile)

        # Create default web root
        webroot = Path("/var/www/html")
        webroot.mkdir(parents=True, exist_ok=True)

        index_html = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to Caddy</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            margin: 0;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
        }
        .container {
            text-align: center;
            padding: 40px;
            background: rgba(255,255,255,0.1);
            border-radius: 20px;
            backdrop-filter: blur(10px);
        }
        h1 { margin-bottom: 10px; }
        p { opacity: 0.9; }
        a { color: #fff; }
    </style>
</head>
<body>
    <div class="container">
        <h1>🚀 Caddy is Running!</h1>
        <p>Your web server is ready to serve content.</p>
        <p>Edit <code>/etc/caddy/Caddyfile</code> to configure your sites.</p>
        <p><a href="https://caddyserver.com/docs/">Documentation</a></p>
    </div>
</body>
</html>
"""

        (webroot / "index.html").write_text(index_html)

        self.logger.info("✓ Configuration created")

    def _configure_firewall(self):
        """Configure UFW for Caddy."""
        self.logger.info("Configuring firewall...")

        self.run("ufw allow 80/tcp comment 'HTTP'", check=False)
        self.run("ufw allow 443/tcp comment 'HTTPS'", check=False)

        self.logger.info("✓ Firewall configured (ports 80, 443)")

    def _start_service(self):
        """Start Caddy service."""
        self.logger.info("Starting Caddy...")

        self.enable_service("caddy")

        self.logger.info("✓ Caddy started")
