"""
Neovim module for terminal-based code editing.

Handles:
- Neovim installation
- Basic configuration
- Plugin manager (lazy.nvim)
"""

import os
from pathlib import Path

from configurator.modules.base import ConfigurationModule


class NeovimModule(ConfigurationModule):
    """
    Neovim installation module.

    Installs Neovim with a modern configuration.
    """

    name = "Neovim"
    description = "Neovim editor with configuration"
    depends_on = ["system"]
    priority = 62
    mandatory = False

    def validate(self) -> bool:
        """Validate Neovim prerequisites."""
        # Check if Neovim is already installed
        if self.command_exists("nvim"):
            result = self.run("nvim --version | head -1", check=False)
            self.logger.info(f"  Found existing Neovim: {result.stdout.strip()}")

        return True

    def configure(self) -> bool:
        """Install and configure Neovim."""
        self.logger.info("Installing Neovim...")

        # 1. Install Neovim
        self._install_neovim()

        # 2. Install dependencies
        self._install_dependencies()

        # 3. Create basic configuration
        self._create_config()

        self.logger.info("✓ Neovim installed")
        return True

    def verify(self) -> bool:
        """Verify Neovim installation."""
        checks_passed = True

        # Check nvim
        result = self.run("nvim --version | head -1", check=False)
        if result.success:
            self.logger.info(f"✓ {result.stdout.strip()}")
        else:
            self.logger.error("Neovim not found!")
            checks_passed = False

        return checks_passed

    def _install_neovim(self):
        """Install Neovim."""
        # Try to install latest from GitHub releases
        version = self.get_config("version", "stable")

        if version == "stable":
            # Install from Debian repos (may be older version)
            self.install_packages(["neovim"])
        else:
            # Install specific version from GitHub
            self._install_from_github(version)

        self.logger.info("✓ Neovim installed")

    def _install_from_github(self, version: str):
        """Install Neovim from GitHub releases."""
        self.logger.info(f"Installing Neovim {version} from GitHub...")

        # Download AppImage
        url = f"https://github.com/neovim/neovim/releases/download/{version}/nvim.appimage"

        self.run(f"curl -fsSL {url} -o /usr/local/bin/nvim", check=True)
        self.run("chmod +x /usr/local/bin/nvim", check=True)

    def _install_dependencies(self):
        """Install Neovim dependencies."""
        packages = [
            "ripgrep",  # For telescope
            "fd-find",  # For telescope
            "nodejs",  # For some LSP servers
            "npm",  # For some LSP servers
        ]

        self.install_packages(packages)

    def _create_config(self):
        """Create basic Neovim configuration."""
        config_dir = Path(os.path.join(self.target_home, ".config/nvim"))
        config_dir.mkdir(parents=True, exist_ok=True)

        init_lua = """-- Neovim Configuration
-- Generated by debian-vps-configurator

-- Set leader key
vim.g.mapleader = " "
vim.g.maplocalleader = " "

-- Basic options
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.mouse = "a"
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.hlsearch = false
vim.opt.wrap = false
vim.opt.breakindent = true
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.scrolloff = 8
vim.opt.signcolumn = "yes"
vim.opt.updatetime = 250
vim.opt.termguicolors = true
vim.opt.clipboard = "unnamedplus"

-- Key mappings
vim.keymap.set("n", "<leader>w", "<cmd>write<cr>", { desc = "Save" })
vim.keymap.set("n", "<leader>q", "<cmd>quit<cr>", { desc = "Quit" })
vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<cr>", { desc = "Clear search" })

-- Bootstrap lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable",
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

-- Plugin specification
local plugins = {
  -- Colorscheme
  {
    "folke/tokyonight.nvim",
    lazy = false,
    priority = 1000,
    config = function()
      vim.cmd.colorscheme("tokyonight-night")
    end,
  },

  -- Status line
  {
    "nvim-lualine/lualine.nvim",
    dependencies = { "nvim-tree/nvim-web-devicons" },
    config = function()
      require("lualine").setup()
    end,
  },

  -- File explorer
  {
    "nvim-tree/nvim-tree.lua",
    dependencies = { "nvim-tree/nvim-web-devicons" },
    config = function()
      require("nvim-tree").setup()
      vim.keymap.set("n", "<leader>e", "<cmd>NvimTreeToggle<cr>", { desc = "File Explorer" })
    end,
  },

  -- Fuzzy finder
  {
    "nvim-telescope/telescope.nvim",
    branch = "0.1.x",
    dependencies = { "nvim-lua/plenary.nvim" },
    config = function()
      local builtin = require("telescope.builtin")
      vim.keymap.set("n", "<leader>ff", builtin.find_files, { desc = "Find Files" })
      vim.keymap.set("n", "<leader>fg", builtin.live_grep, { desc = "Live Grep" })
      vim.keymap.set("n", "<leader>fb", builtin.buffers, { desc = "Buffers" })
    end,
  },

  -- Git signs
  {
    "lewis6991/gitsigns.nvim",
    config = function()
      require("gitsigns").setup()
    end,
  },

  -- Treesitter
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    config = function()
      require("nvim-treesitter.configs").setup({
        ensure_installed = { "lua", "python", "javascript", "typescript", "html", "css", "json", "yaml", "bash" },
        highlight = { enable = true },
        indent = { enable = true },
      })
    end,
  },

  -- Auto pairs
  {
    "windwp/nvim-autopairs",
    event = "InsertEnter",
    config = true,
  },

  -- Which key
  {
    "folke/which-key.nvim",
    event = "VeryLazy",
    config = function()
      require("which-key").setup()
    end,
  },
}

-- Load plugins
require("lazy").setup(plugins)

print("Neovim configured! Press <Space> to see available commands.")
"""

        # Write config
        config_file = config_dir / "init.lua"
        # Use our write_file to handle dry-run (though it takes string path)
        self.write_file(str(config_file), init_lua)

        # Ensure permissions if not current user
        if self.target_user != os.environ.get("USER"):
            self.run(
                f"chown -R {self.target_user}:{self.target_user} {self.target_home}/.config",
                check=False,
            )

        self.logger.info("✓ Neovim configuration created")
        self.logger.info(f"  Config location: {config_file}")
