import os
from unittest.mock import Mock

from configurator.modules.desktop import DesktopModule

# Mock dependencies to instantiate module without running it
mock_logger = Mock()
mock_rollback = Mock()
mock_dry_run = Mock()
mock_dry_run.is_enabled = False

module = DesktopModule(
    config={"desktop": {"xrdp": {"max_bpp": 24}}},  # Ensure default optimized config
    logger=mock_logger,
    rollback_manager=mock_rollback,
    dry_run_manager=mock_dry_run,
)

xrdp_content = module._generate_xrdp_ini()
sesman_content = module._generate_sesman_ini()
xsession_content = """#!/bin/bash
# XRDP Session Configuration
# Generated by debian-vps-workstation configurator

# Environment cleanup
export NO_AT_BRIDGE=1
export GNOME_KEYRING_CONTROL=""
export GTK_MODULES=""

# Session variables
export XDG_SESSION_TYPE=x11
export XDG_SESSION_DESKTOP=xfce
export XDG_CURRENT_DESKTOP=XFCE
export DESKTOP_SESSION=xfce

# Cursor fix
export XCURSOR_THEME=Adwaita
export XCURSOR_SIZE=24

# Disable screen saver and power management for remote sessions
xset s off
xset -dpms
xset s noblank

# Set keyboard repeat rate (faster response)
xset r rate 200 30

# Cursor rendering fix
xsetroot -cursor_name left_ptr

# Start XFCE session
exec startxfce4
"""


os.makedirs("deploy_configs", exist_ok=True)

with open("deploy_configs/xrdp.ini", "w") as f:
    f.write(xrdp_content)

with open("deploy_configs/sesman.ini", "w") as f:
    f.write(sesman_content)

with open("deploy_configs/.xsession", "w") as f:
    f.write(xsession_content)

print("Configurations regenerated in deploy_configs/")
